BLOCKING={"LOCKED_ELEMENT_CONFLICT","POST_EDIT_REJECTED","POST_EDIT_UNAUTHORIZED_DELTA","NO_CAPABLE_PROVIDER","PROVIDER_ADAPTER_MISSING"}
def classify(failure_code): return "BLOCKING" if failure_code in BLOCKING else "NON_BLOCKING"
